### ISSUE TITLE
Card Backs and centre cards

### ISSUE THREAD

**Issue by karan1276** [philo-jh/MTG-Proxy-Generator#1]
It would be great to add card backs. And also centre the cards so front and back are aligned.

**Comment by philo-jh** [comment]
I think card backs are a fine idea for print-testing purposes (sizing / does it fit), but I'm not including card backs & centering for the purpose of recreating magic cards. This app creates proxies meant to be printed on paper & cut-out for testing / fun purposes and I don't want it being used to easily create counterfeit cards.
