### ISSUE TITLE
Missing Tokens

### ISSUE THREAD

**Issue by SilverSix** [philo-jh/MTG-Proxy-Generator#2]
When creating proxies of tokens, those that have several types under the same name do not show all of the options available.  Examples like Beast, Angel, Zombie which have several variations have been tested, but only a single print is shown.

Most angels are 4/4 but the default and only option is the OGW token that is a 3/3 angel. Likewise, there are many, many zombies, but the default one is the one from Born from the Gods, an Enchantment Creature.

How to replicate:
Attempt to produce proxies of tokens with several different variations, not just prints. For instance, all sliver tokens are shown since all sliver tokens are 1/1 colorless creatures. Zombies and angels, on the other hand, have varying creature types, colors, and power/toughness, so they only print from a single set.

Also, as a two-cent contribution, if the user could edit the art of several cards at once instead of one by one, it would streamline the process and user experience.

**Comment by LunaMoonborn** [comment]
A little to add to this, if you input '1 Beast' you get the 6/6 Artifact Beast from Kaladesh with no other options. If you instead input '1 Beast (MT15)' you get 26 different 3/3 Beasts, but sadly none of them are the 3/3 Black Beast with Deathtouch from M15.

**Comment by philo-jh** [comment]
I am working on an overhaul of this and will include token support. I plan on allowing you to search for tokens in a similar manner to how you would just search for a card. I also want to allow the user to have the app generate the tokens associated with a given card.

**Comment by philo-jh** [comment]
I have solved this issue by implementing the -code flag. You can now search for any card by it's [set-code]/[collector-number] found on ScryFall. For example @LunaMoonborn, the 3/3 Black Beast with Deathtouch from M15 has a set-code of [TM15] and a collector-number of [5]. You can now make this token with:

tm15/5 -code

or if you want 4 copies of this token...

4 tm15/5 -code

**Comment by LunaMoonborn** [comment]
@philo-jh Awesome, this is great. Thank you so much.
